insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')



insert into tb_categories(title) values('Romaticism')
insert into tb_categories(title) values('Novelism')
insert into tb_categories(title) values('Friendzonism')
insert into tb_categories(title) values('Crazyism')
insert into tb_categories(title) values('Lovelyism')
insert into tb_categories(title) values('Stupidism')
insert into tb_categories(title) values('Adorablism')
